/*
 * BswScheduler.h
 *
 * [Educational Implementation] tiny cyclic scheduler driven by simulated time.
 * Real AUTOSAR counterpart: OS (e.g. RTA-OS) tasks activated by alarms or
 * schedule tables, whose bodies are generated by the RTE/SchM and call the
 * BSW MainFunctions and SW-C runnables; plus the interrupt controller that
 * dispatches CAN ISRs. Typical periods: Can/CanTp 1-5 ms, NvM 5-10 ms, Dcm 10 ms.
 */
#ifndef BSW_SCHEDULER_H
#define BSW_SCHEDULER_H

#include "Std_Types.h"

/* Advance simulated time by 1 ms and run everything that is due. */
void BswScheduler_Tick1ms(void);

#endif /* BSW_SCHEDULER_H */
