/*
 * Can_Cfg.c
 *
 * [Educational Implementation] hand-written "as if generated".
 * Real AUTOSAR counterpart: Can_PBcfg.c generated by the MCAL configurator.
 * In a real RS-CANFD driver each RECEIVE HOH becomes one or more receive
 * rules (GAFLIDj / GAFLMj / GAFLP0j / GAFLP1j) and each TRANSMIT HOH maps
 * to a TX buffer (TMIDp / TMPTRp / TMDFp / TMCp) or a TX/RX FIFO.
 */
#include "Can.h"

static const Can_ControllerConfigType Can_Controllers[CAN_NUM_CONTROLLERS] = {
    { CanConf_CanController_CAN0, 500u }
};

static const Can_HardwareObjectConfigType Can_Hoh[CAN_NUM_HOH] = {
    /* id                          type                        ctrl code    mask    hw  name */
    { CanConf_HRH_DiagPhysReq_7E0, CAN_OBJECT_TYPE_RECEIVE,   0u, 0x7E0u, 0x7FFu, 0u, "HRH0(0x7E0 phys req)" },
    { CanConf_HRH_DiagFuncReq_7DF, CAN_OBJECT_TYPE_RECEIVE,   0u, 0x7DFu, 0x7FFu, 1u, "HRH1(0x7DF func req)" },
    { CanConf_HTH_DiagResp,        CAN_OBJECT_TYPE_TRANSMIT,  0u, 0u,     0u,     0u, "HTH2(TX buffer 0)" }
};

const Can_ConfigType Can_Config = {
    Can_Controllers, CAN_NUM_CONTROLLERS,
    Can_Hoh, CAN_NUM_HOH
};
