#!/usr/bin/env python3
"""
test_generator.py - self-tests of generator/gen_rte.py.  [Educational Implementation]

What is verified:
  * golden files   : the generator output equals the committed gen/<Ecu>/ (nobody edited a generated file, nobody forgot to regenerate)
  * determinism    : two runs give byte-identical output (no time stamps, no dict-order noise)
  * banner         : every generated file starts with the "GENERATED ... do not edit" banner
  * validation     : each class of configuration mistake is reported with a clear message and nothing is generated
                       unmapped RTE event, unconnected port, task priority conflict, data type mismatch,
                       resource ceiling too low, timing period vs alarm cycle, CAN id mismatch between Com and CanIf
  * contract       : a SWC that uses an RTE API it is not configured for does not compile (SWS_Rte_01004 behaviour)
Run: python tests/unit/test_generator.py   (exit code 0 = pass); also run by tools/run_mini_autosar.py --step unit
"""
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "generator"))

import gen_rte                                            # noqa: E402
from arxml_model import GenError                          # noqa: E402

SWC = ROOT / "config/swc/SwcTypes.arxml"
SYS = ROOT / "config/system/System.arxml"
ECUC = {"LightEcu": ROOT / "config/ecuc/LightEcu.ecuc.json", "SensorEcu": ROOT / "config/ecuc/SensorEcu.ecuc.json"}


def gen(ecu, swc=SWC, system=SYS, ecuc=None):
    return gen_rte.generate(str(swc), str(system), str(ecuc or ECUC[ecu]))


class Mutated(object):
    """temp copies of the inputs with a text/JSON mutation applied."""

    def __init__(self):
        self.dir = pathlib.Path(tempfile.mkdtemp(prefix="genmut_"))
        self.swc, self.sys = self.dir / "swc.arxml", self.dir / "sys.arxml"
        shutil.copy(SWC, self.swc)
        shutil.copy(SYS, self.sys)
        self.ecuc = {}

    def text(self, which, old, new):
        p = {"swc": self.swc, "sys": self.sys}[which]
        t = p.read_text(encoding="utf-8")
        assert old in t, "mutation anchor not found: %r" % old
        p.write_text(t.replace(old, new, 1), encoding="utf-8")

    def json(self, ecu, fn):
        p = self.ecuc.get(ecu)
        if p is None:
            p = self.dir / (ecu + ".json")
            self.ecuc[ecu] = p
            shutil.copy(ECUC[ecu], p)
        d = json.loads(p.read_text(encoding="utf-8"))
        fn(d)
        p.write_text(json.dumps(d), encoding="utf-8")

    def run(self, ecu):
        return gen(ecu, self.swc, self.sys, self.ecuc.get(ecu, ECUC[ecu]))

    def cleanup(self):
        shutil.rmtree(self.dir, ignore_errors=True)


class GoldenAndDeterminism(unittest.TestCase):
    def test_golden_equals_committed(self):
        for ecu in ECUC:
            files = gen(ecu)
            committed = ROOT / "gen" / ecu
            self.assertTrue(committed.is_dir(), "gen/%s missing: run tools/run_mini_autosar.py --step gen" % ecu)
            on_disk = sorted(f.name for f in committed.iterdir() if f.suffix in (".c", ".h"))
            self.assertEqual(sorted(files), on_disk, "file set of gen/%s differs from generator output" % ecu)
            for name, text in files.items():
                self.assertEqual((committed / name).read_bytes().decode("utf-8").replace("\r\n", "\n"), text,
                                 "gen/%s/%s is stale or was edited: regenerate" % (ecu, name))

    def test_deterministic(self):
        for ecu in ECUC:
            self.assertEqual(gen(ecu), gen(ecu))

    def test_expected_file_set(self):
        must = ["Rte_Type.h", "Rte.h", "Rte_Cbk.h", "Rte.c", "Rte_Tasks.c", "Os_Cfg.h", "Os_Cfg.c", "Com_Cfg.h", "Com_Cfg.c",
                "PduR_Cfg.h", "PduR_Cfg.c", "CanIf_Cfg.h", "CanIf_Cfg.c", "Can_Cfg.h", "Can_Cfg.c", "EcuM_Cfg.h", "EcuM_Cfg.c",
                "BswM_Cfg.h", "BswM_Cfg.c", "Mcu_Cfg.h", "Mcu_Cfg.c", "Port_Cfg.h", "Port_Cfg.c", "Dio_Cfg.h", "Dio_Cfg.c",
                "Adc_Cfg.h", "Adc_Cfg.c"]
        light = gen("LightEcu")
        for m in must + ["Rte_LightControlSWC.h", "Rte_LightActuatorSWC.h", "Rte_OdometerSWC.h", "Rte_LightControlSWC_Type.h"]:
            self.assertIn(m, light)
        self.assertIn("Rte_SpeedSensorSWC.h", gen("SensorEcu"))

    def test_banner(self):
        for ecu in ECUC:
            for name, text in gen(ecu).items():
                head = text.split("*/", 1)[0]
                self.assertTrue(text.startswith("/*\n * %s\n" % name), name)
                self.assertIn("GENERATED by generator/gen_rte.py from config/swc/SwcTypes.arxml", head, name)
                self.assertIn("do not edit", head, name)
                self.assertIn("[Educational Implementation]", head, name)
                self.assertIn("Corresponds to AUTOSAR", head, name)

    def test_semantics_in_output(self):
        light = gen("LightEcu")
        t = light["Rte_Tasks.c"]
        self.assertIn("TASK(Task_LightCtl)", t)
        # RtePositionInTask order 1,2,3
        self.assertLess(t.index("LightCtl_Run20ms();"), t.index("LightCtl_OnSpeed();"))
        self.assertLess(t.index("LightCtl_OnSpeed();"), t.index("LightCtl_OnModeSwitch();"))
        self.assertIn("Rte_Mode_EcuMode != RTE_MODE_EcuMode_POST_RUN", t)           # disabledInMode
        self.assertIn("Rte_CopyIn_LightCtl_OnSpeed();", t)                            # implicit read
        self.assertIn("MINI_CODE_FAST ISR(Isr_CanRx)", t)
        osc = light["Os_Cfg.c"]
        self.assertIn(".ceilingPriority = 3u", osc)                                  # max(Task_LightCtl 3, Task_LightAct 2)
        self.assertIn("Rte_COMCbk_VehicleSpeed", light["Com_Cfg.c"])
        self.assertIn("void Rte_COMCbk_VehicleSpeed(void)", light["Rte_Cbk.h"])
        self.assertIn("(void)SetEvent(Task_LightCtl, Ev_LightCtl_VehicleSpeed);", light["Rte.c"])
        self.assertIn("(void)GetResource(Res_EA_Odo);", light["Rte.c"])
        self.assertIn("return IoHwAb_SetHeadlight(State);", light["Rte.c"])
        sensor = gen("SensorEcu")
        self.assertIn("Rte_CopyOut_SpeedSensor_Run10ms();", sensor["Rte_Tasks.c"])
        self.assertIn("return IoHwAb_GetWheelSpeed(Raw);", sensor["Rte.c"])
        self.assertIn("OS_NUM_RESOURCES    0u", sensor["Os_Cfg.h"])


class Validation(unittest.TestCase):
    def expect(self, ecu, mut, *needles):
        m = Mutated()
        try:
            mut(m)
            with self.assertRaises(GenError) as cm:
                m.run(ecu)
            msg = "\n".join(cm.exception.errors)
            for n in needles:
                self.assertIn(n, msg)
        finally:
            m.cleanup()

    def test_unmapped_event(self):
        def mut(m):
            m.json("LightEcu", lambda d: d["Rte"]["RteEventToTaskMapping"].__delitem__(1))   # DRE_LightCtl_VehicleSpeed
        self.expect("LightEcu", mut, "DRE_LightCtl_VehicleSpeed", "has no RteEventToTaskMapping")

    def test_unconnected_port(self):
        def mut(m):
            a = '<ASSEMBLY-SW-CONNECTOR><SHORT-NAME>C_HeadlightCmd</SHORT-NAME>'
            m.text("sys", a, '<ASSEMBLY-SW-CONNECTOR><SHORT-NAME>C_HeadlightCmd</SHORT-NAME><DISABLED>1</DISABLED>')
            m.text("sys", "<COMPONENT>LightControl</COMPONENT><PORT>P_HeadlightCmd</PORT>", "<COMPONENT>Nobody</COMPONENT><PORT>P_X</PORT>")
        self.expect("LightEcu", mut, "not connected")

    def test_task_priority_conflict(self):
        def mut(m):
            def f(d):
                for t in d["Os"]["OsTask"]:
                    if t["name"] == "Task_LightAct":
                        t["priority"] = 3
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "priority conflict", "Task_LightAct", "Task_LightCtl")

    def test_data_type_mismatch_signal(self):
        def mut(m):
            m.text("swc", '<SHORT-NAME>AmbientLight</SHORT-NAME><TYPE-TREF>/DataTypes/uint8</TYPE-TREF>',
                   '<SHORT-NAME>AmbientLight</SHORT-NAME><TYPE-TREF>/DataTypes/uint16</TYPE-TREF>')
        self.expect("LightEcu", mut, "data type mismatch", "AmbientLight")

    def test_signal_vs_isignal_mismatch(self):
        def mut(m):
            def f(d):
                for s in d["Com"]["ComSignal"]:
                    if s["name"] == "VehicleSpeed":
                        s["bitSize"] = 8
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "ComSignal VehicleSpeed", "I-SIGNAL")

    def test_resource_ceiling_too_low(self):
        def mut(m):
            def f(d):
                d["Os"]["OsResource"][0]["accessedBy"] = ["Task_LightAct"]
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "Res_EA_Odo", "Task_LightCtl", "ceiling")

    def test_period_vs_alarm(self):
        def mut(m):
            def f(d):
                for a in d["Os"]["OsAlarm"]:
                    if a["name"] == "Alarm_LightCtl20ms":
                        a["autostart"]["cycle"] = 25
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "TimingEvent", "period 20 ms", "cycle 25")

    def test_can_id_mismatch(self):
        def mut(m):
            def f(d):
                d["CanIf"]["CanIfRxPduCfg"][0]["canId"] = "0x102"
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "CAN id mismatch")

    def test_extended_task_needs_autostart(self):
        def mut(m):
            def f(d):
                for t in d["Os"]["OsTask"]:
                    if t["name"] == "Task_LightCtl":
                        t["autostart"] = []
            m.json("LightEcu", f)
        self.expect("LightEcu", mut, "EXTENDED but not autostarted")

    def test_all_errors_reported_together(self):
        m = Mutated()
        try:
            def f(d):
                d["Rte"]["RteEventToTaskMapping"].__delitem__(1)
                for t in d["Os"]["OsTask"]:
                    if t["name"] == "Task_LightAct":
                        t["priority"] = 3
            m.json("LightEcu", f)
            with self.assertRaises(GenError) as cm:
                m.run("LightEcu")
            self.assertGreaterEqual(len(cm.exception.errors), 2)
        finally:
            m.cleanup()


class Contract(unittest.TestCase):
    """SWS_Rte_01004: only the access points configured for a SWC exist in its application header."""

    def cc(self, snippet, ecu="LightEcu", swc_hdr="Rte_LightActuatorSWC.h", define="MINI_ECU_B"):
        gcc = shutil.which("gcc")
        if not gcc:
            self.skipTest("no host gcc")
        d = pathlib.Path(tempfile.mkdtemp(prefix="genctr_"))
        try:
            files = gen(ecu)
            for n, t in files.items():
                (d / n).write_text(t, encoding="utf-8")
            (d / "t.c").write_text('#include "%s"\n%s\n' % (swc_hdr, snippet), encoding="utf-8")
            inc = [str(ROOT / x) for x in ["include", "os/include", "rte", "bsw/com", "bsw/pdur", "bsw/det", "bsw/ecum", "bsw/bswm",
                                           "bsw/schm", "ecual/canif", "ecual/iohwab", "mcal/can", "mcal/mcu", "mcal/port",
                                           "mcal/dio", "mcal/adc", "mcal/mmio", "sim/include"]]
            cmd = [gcc, "-std=c99", "-Wall", "-Wextra", "-Werror", "-DMINI_PLATFORM_HOST", "-D" + define, "-I" + str(d)] + ["-I" + i for i in inc] + \
                  ["-c", str(d / "t.c"), "-o", str(d / "t.o")]
            p = subprocess.run(cmd, capture_output=True, text=True)
            return p.returncode, p.stdout + p.stderr
        finally:
            shutil.rmtree(d, ignore_errors=True)

    def test_declared_api_compiles(self):
        rc, out = self.cc("void f(void){ uint8 c; uint32 d; (void)Rte_Read_R_HeadlightCmd_HeadlightCmd(&c); "
                          "(void)Rte_Call_R_Odometer_GetDistance(&d); (void)Rte_Write_P_OdometerDistance_Distance(d); }")
        self.assertEqual(rc, 0, out)

    def test_undeclared_api_does_not_compile(self):
        # LightActuatorSWC has no P_HeadlightCmd and no UpdateSpeed call point: these must be compile errors
        rc, out = self.cc("void f(void){ (void)Rte_Write_P_HeadlightCmd_HeadlightCmd(1u); }")
        self.assertNotEqual(rc, 0)
        rc, out = self.cc("void f(void){ (void)Rte_Call_R_Odometer_UpdateSpeed(1u); }")
        self.assertNotEqual(rc, 0)
        rc, out = self.cc("void f(void){ (void)Rte_Mode_R_EcuMode_EcuMode(); }")
        self.assertNotEqual(rc, 0)

    def test_swc_headers_only_rte_and_trace(self):
        for f in (ROOT / "swc").glob("*/*.c"):
            incs = [l.split('"')[1] for l in f.read_text(encoding="utf-8").splitlines() if l.startswith("#include")]
            self.assertEqual(sorted(i for i in incs if i != "Trace.h"), ["Rte_%s.h" % f.stem], f.name)


if __name__ == "__main__":
    unittest.main(verbosity=2)
