/*
 * BswM.h
 *
 * [Educational Implementation]
 * Real AUTOSAR counterpart: BSW Mode Manager (AUTOSAR_CP_SWS_BSWModeManager; BswM_Init 8.3.16,
 * BswM_EcuM_CurrentState 8.3.9, BswM_RequestMode 8.3.26). Implemented: a minimal rule engine
 *   mode request ports --(condition: value == expected)--> BswMRule --> action list (true/false)
 * with immediate evaluation for pushed requests (EcuM state, BswM_RequestMode) and polled evaluation
 * for Com signal requests in BswM_MainFunction (BSWM_SRC_COM_SIGNAL). Action items are plain
 * function pointers (the real BswMUserCallout / BswMComMIpduGroupSwitch / BswMRteModeRequest actions
 * collapsed into one kind); their bodies live in the GENERATED BswM_Cfg.c.
 * Not implemented: logical expressions, timers, arbitration, deferred rules, NvM/J1939/... ports.
 * Owner: agent C (BswM.c); BswM_Cfg.c/.h generated by agent D.
 */
#ifndef BSWM_H
#define BSWM_H

#include "Std_Types.h"
#include "ComStack_Types.h"
#include "EcuM.h"
#include "BswM_Cfg.h"    /* generated: BSWM_NUM_RULES, BSWM_NUM_REQUEST_USERS */

typedef uint8 BswM_UserType;
typedef uint16 BswM_ModeType;

typedef enum {                 /* source of the mode request that a rule condition looks at */
    BSWM_SRC_ECUM_STATE = 0,   /* BswM_EcuM_CurrentState (pushed)     arg = unused */
    BSWM_SRC_REQUEST,          /* BswM_RequestMode (pushed)           arg = BswM_UserType */
    BSWM_SRC_COM_SIGNAL        /* Com_ReceiveSignal (polled, uint8)   arg = Com_SignalIdType */
} BswM_SourceType;

typedef enum { BSWM_RULE_UNDEFINED = 0, BSWM_RULE_FALSE, BSWM_RULE_TRUE } BswM_RuleStateType;

typedef struct {
    Std_ReturnType (*fn)(void);           /* action; return value logged only */
    const char      *name;                /* for the trace line "BSWM ACTION <name>" */
} BswM_ActionItemType;

typedef struct {
    uint8                      numItems;
    const BswM_ActionItemType *items;     /* executed in order; "CONDITION" execution semantics */
} BswM_ActionListType;

typedef struct {
    const char                *name;      /* e.g. "R_Startup" */
    BswM_SourceType            source;
    uint16                     arg;
    uint32                     expected;  /* condition TRUE when requested value == expected */
    const BswM_ActionListType *trueList;  /* executed on transition to TRUE (and when first evaluated TRUE) */
    const BswM_ActionListType *falseList; /* executed on transition to FALSE; may be NULL_PTR */
} BswM_RuleType;

typedef struct {
    uint8                numRules;
    const BswM_RuleType *rules;
    uint8                numRequestUsers;
} BswM_ConfigType;
extern const BswM_ConfigType BswM_Config;        /* generated BswM_Cfg.c */

void BswM_Init(const BswM_ConfigType *ConfigPtr);     /* resets rule states; does NOT start anything itself */
void BswM_Deinit(void);
void BswM_EcuM_CurrentState(EcuM_StateType CurrentState);  /* pushed by EcuM at every state change; evaluates rules */
void BswM_RequestMode(BswM_UserType requestingUser, BswM_ModeType requestedMode);
void BswM_MainFunction(void);                         /* polled sources; scheduled every 10 ms */
void BswM_GetVersionInfo(Std_VersionInfoType *versioninfo);

#endif /* BSWM_H */
