"""
emit_os.py - emits Os_Cfg.h / Os_Cfg.c from the ECUC "Os" part (OsTask, OsAlarm, OsCounter, OsResource, OsIsr, OsHooks).

[Educational Implementation]
Real AUTOSAR counterpart: the OS generator (OIL compiler in OSEK, OS configurator in AUTOSAR). The kernel never parses
a configuration; it reads constant tables that the generator compiled from it. Resource ceiling priorities are COMPUTED
here (priority ceiling protocol: ceiling = max priority of every task that may take the resource), not typed in.
"""
from emit_util import banner, W
from arxml_model import parse_c_int


def _modes_mask(ecu, names):
    app = ecu.ecuc["Os"]["OsOS"].get("appModes", ["OSDEFAULTAPPMODE"])
    m = 0
    for n in names:
        m |= 1 << app.index(n)
    return m


def gen_os_cfg_h(ecu):
    os_ = ecu.ecuc["Os"]
    w = W()
    fn = "Os_Cfg.h"
    w(banner(fn, ecu, "OS object identifiers and counts of ECU %s. Included by Os.h (after the OS types), so SWC-independent code "
             "like the RTE can name tasks, alarms, events and resources by their ECUC short names. Object ids are the index into "
             "the tables of Os_Cfg.c; event masks are one bit each; resource id 0 is the implicit RES_SCHEDULER." % ecu.name,
             "OS generator output (OIL / OsConfig -> Os_Cfg.h)").rstrip("\n"))
    w("#ifndef OS_CFG_H")
    w("#define OS_CFG_H")
    w()
    w("/* ---- counts (array sizes in Os_Cfg.c, also used by the kernel for its run-time tables) ---- */")
    w("#define OS_NUM_TASKS        %du" % len(ecu.tasks))
    w("#define OS_NUM_COUNTERS     %du" % len(os_["OsCounter"]))
    w("#define OS_NUM_ALARMS       %du" % len(os_.get("OsAlarm", [])))
    w("#define OS_NUM_RESOURCES    %du" % len(os_.get("OsResource", [])))
    w("#define OS_NUM_ISRS         %du" % len(os_.get("OsIsr", [])))
    w()
    h = os_.get("OsHooks", {})
    w("/* ---- hooks (OsHooks): the kernel calls a hook only if enabled; bodies are in integration/Os_Hooks.c ---- */")
    for k, n in (("startup", "STARTUPHOOK"), ("error", "ERRORHOOK"), ("shutdown", "SHUTDOWNHOOK"), ("preTask", "PRETASKHOOK"), ("postTask", "POSTTASKHOOK")):
        w("#define OS_USE_%-13s %d" % (n, 1 if h.get(k) else 0))
    w()
    w("/* ---- tasks (OsTask): id = index in Os_Config.tasks; the Idle task is internal to the kernel and has no id here ---- */")
    for t in ecu.tasks.values():
        w("#define %-22s ((TaskType)%du)   /* %s, priority %d */" % (t.name, t.index, t.type, t.prio))
    w()
    w("/* ---- counters / alarms / resources / ISRs ---- */")
    for i, c in enumerate(os_["OsCounter"]):
        w("#define %-22s ((CounterType)%du)" % (c["name"], i))
    for i, a in enumerate(os_.get("OsAlarm", [])):
        w("#define %-22s ((AlarmType)%du)" % (a["name"], i))
    for i, r in enumerate(os_.get("OsResource", [])):
        w("#define %-22s ((ResourceType)%du)   /* ceiling priority %d */" % (r["name"], i + 1, ecu.ceilings[r["name"]]))
    for i, r in enumerate(os_.get("OsIsr", [])):
        w("#define %-22s ((ISRType)%du)" % (r["name"], i))
    w()
    if ecu.ev_masks:
        w("/* ---- events (OsEvent): one bit each; the owning task is named in OsTaskEvent ---- */")
        for n, m in ecu.ev_masks.items():
            w("#define %-26s ((EventMaskType)0x%Xu)" % (n, m))
        w()
    w("#endif /* OS_CFG_H */")
    return w.text()


def gen_os_cfg_c(ecu):
    os_ = ecu.ecuc["Os"]
    w = W()
    fn = "Os_Cfg.c"
    w(banner(fn, ecu, "The constant OS configuration of ECU %s: THE contract between this generator and the kernel (see "
             "os/include/Os_CfgTypes.h). Everything the kernel needs - tasks with priorities/stacks, alarms with autostart "
             "parameters, resource ceilings, ISRs - is data in this file; the kernel contains no application knowledge." % ecu.name,
             "OS generator output (Os_Cfg.c)").rstrip("\n"))
    w('#include "Os.h"')
    w('#include "Os_CfgTypes.h"')
    w('#include "MemMap.h"')
    w()
    w("/* task bodies live in Rte_Tasks.c (generated by the RTE generator, SWS_Rte_06200); TASK(x) = void Os_Task_x(void) */")
    for t in ecu.tasks.values():
        w("DeclareTask(%s);" % t.name)
    for i in os_.get("OsIsr", []):
        w("DeclareISR(%s);" % i["name"])
    w()
    w("/* ---- task stacks (OsTaskStack): word arrays in section .os_stack; the target port starts a task with SP at the top ---- */")
    for t in ecu.tasks.values():
        w("static Os_StackElementType Os_Stack_%s[%d] MINI_VAR_OS_STACK;" % (t.name, t.stack))
    w()
    w("/* ---- tasks ---- */")
    w("static const Os_TaskCfgType Os_Tasks[OS_NUM_TASKS] MINI_CONST_CFG = {")
    for t in ecu.tasks.values():
        w("    { /* %s */" % t.name)
        w('      .name = "%s",' % t.name)
        w("      .entry = Os_Task_%s," % t.name)
        w("      .priority = %du,                 /* higher number = more urgent; unique per ECU (checked by the generator) */" % t.prio)
        w("      .maxActivations = %du,           /* OsTaskActivation; extended tasks must be 1 */" % t.act)
        w("      .extended = %s,                   /* extended = may call WaitEvent */" % ("TRUE" if t.type == "EXTENDED" else "FALSE"))
        w("      .schedule = %s," % ("OS_SCHED_FULL" if t.sched == "FULL" else "OS_SCHED_NON"))
        w("      .autostartModes = 0x%Xu,         /* bit n: started by StartOS in AppMode n */" % _modes_mask(ecu, t.autostart))
        w("      .stackBase = Os_Stack_%s," % t.name)
        w("      .stackWords = %du }%s" % (t.stack, "," if t.index < len(ecu.tasks) - 1 else ""))
    w("};")
    w()
    w("/* ---- counters (OsCounter) ---- */")
    w("static const Os_CounterCfgType Os_Counters[OS_NUM_COUNTERS] MINI_CONST_CFG = {")
    for c in os_["OsCounter"]:
        w("    { .maxAllowedValue = %du, .ticksPerBase = %du, .minCycle = %du, .hardware = %s }, /* %s: driven by the system tick */" % (
            c["maxAllowedValue"], c["ticksPerBase"], c["minCycle"], "TRUE" if c.get("hardware") else "FALSE", c["name"]))
    w("};")
    w()
    alarms = os_.get("OsAlarm", [])
    if alarms:
        w("/* ---- alarms (OsAlarm): these are the time base of every TimingEvent / BSW MainFunction. 'autostart' = armed by StartOS,")
        w(" *      start = offset in ticks (RteActivationOffset), cycle = period in ticks. 1 tick = %d us. ---- */" % os_["OsOS"]["tickDurationUs"])
        w("static const Os_AlarmCfgType Os_Alarms[OS_NUM_ALARMS] MINI_CONST_CFG = {")
        for k, a in enumerate(alarms):
            act = a["action"]
            au = a.get("autostart")
            kind = {"ACTIVATETASK": "OS_ALARM_ACTIVATETASK", "SETEVENT": "OS_ALARM_SETEVENT"}[act["type"]]
            w("    { /* %s */" % a["name"])
            w('      .name = "%s",' % a["name"])
            w("      .counter = %s," % a["counter"])
            w("      .action = %s," % kind)
            w("      .task = %s," % act["task"])
            w("      .event = %s," % (act["event"] if act["type"] == "SETEVENT" else "0u"))
            w("      .callback = NULL_PTR,")
            w("      .incCounter = 0u,")
            w("      .autostart = %s," % ("TRUE" if au else "FALSE"))
            w("      .autostartAbsolute = %s," % ("TRUE" if au and au["type"] == "ABS" else "FALSE"))
            w("      .autostartTime = %du," % (au["start"] if au else 0))
            w("      .autostartCycle = %du," % (au["cycle"] if au else 0))
            w("      .autostartModes = 0x%Xu }%s" % (_modes_mask(ecu, au["mode"]) if au else 0, "," if k < len(alarms) - 1 else ""))
        w("};")
        w()
    ress = os_.get("OsResource", [])
    if ress:
        w("/* ---- resources (OsResource): ceilingPriority is COMPUTED = max priority of every task that can reach the resource.")
        w(" *      Holding the resource raises the holder to the ceiling, so no accessor can preempt another inside the critical section. ---- */")
        w("static const Os_ResourceCfgType Os_Resources[OS_NUM_RESOURCES] MINI_CONST_CFG = {")
        for k, r in enumerate(ress):
            acc = sorted(set(r.get("accessedBy", [])) | set(r.get("_computedAccessors", [])), key=lambda n: -ecu.tasks[n].prio)
            w('    { .name = "%s", .ceilingPriority = %du }%s   /* accessors: %s */' % (
                r["name"], ecu.ceilings[r["name"]], "," if k < len(ress) - 1 else "",
                ", ".join("%s(%d)" % (n, ecu.tasks[n].prio) for n in acc)))
        w("};")
        w()
    isrs = os_.get("OsIsr", [])
    if isrs:
        w("/* ---- ISRs (OsIsr, category 2): handler = Os_Isr_<name> from Rte_Tasks.c ---- */")
        w("static const Os_IsrCfgType Os_Isrs[OS_NUM_ISRS] MINI_CONST_CFG = {")
        for k, i in enumerate(isrs):
            w('    { .name = "%s", .handler = Os_Isr_%s, .irqNumber = %du, .nvicPriority = 0x%Xu }%s' % (
                i["name"], i["name"], i["irq"], parse_c_int(i["nvicPriority"]), "," if k < len(isrs) - 1 else ""))
        w("};")
        w()
    w("/* ---- the configuration root read by the kernel ---- */")
    w("const Os_ConfigType Os_Config = {")
    w("    .numTasks = OS_NUM_TASKS,")
    w("    .numCounters = OS_NUM_COUNTERS,")
    w("    .numAlarms = OS_NUM_ALARMS,")
    w("    .numResources = OS_NUM_RESOURCES,")
    w("    .numIsrs = OS_NUM_ISRS,")
    w("    .tasks = Os_Tasks,")
    w("    .counters = Os_Counters,")
    w("    .alarms = %s," % ("Os_Alarms" if alarms else "NULL_PTR"))
    w("    .resources = %s," % ("Os_Resources" if ress else "NULL_PTR"))
    w("    .isrs = %s," % ("Os_Isrs" if isrs else "NULL_PTR"))
    w("    .systemCounter = %s," % os_["OsCounter"][0]["name"])
    w("    .tickDurationUs = %du" % os_["OsOS"]["tickDurationUs"])
    w("};")
    return w.text()
