"""
emit_util.py - shared helpers of the emitters: the standard file banner and a tiny line collector.

[Educational Implementation]
Every generated file starts with the same banner so that nobody edits it by accident and so that a
reader learns which real-AUTOSAR step the file corresponds to.
"""
import textwrap

RTE_PHASE = "RTE generation phase (SWS_Rte_01004 application header / SWS_Rte_06200 task bodies)"
CFG_PHASE = "BSW configurator output (ECUC -> <Module>_Cfg.[ch], e.g. EB tresos / DaVinci Configurator)"


def banner(fname, ecu, what, counterpart, notes=()):
    """Standard header of every generated file."""
    lines = ["/*",
             " * %s" % fname,
             " *",
             " * GENERATED by generator/gen_rte.py from config/swc/SwcTypes.arxml, config/system/System.arxml,",
             " * %s - do not edit." % ecu.ecuc_file,
             " * [Educational Implementation]",
             " * Corresponds to AUTOSAR %s." % counterpart,
             " *"]
    for w in what.split("\n"):
        if w.strip() == "":
            lines.append(" *")
        else:
            for x in textwrap.wrap(w, 98, subsequent_indent=("    " if w.startswith(" ") else "")) or [""]:
                lines.append(" * " + x)
    for n in notes:
        lines.append(" * " + n)
    lines.append(" */")
    return "\n".join(lines) + "\n"


class W(object):
    """line collector"""

    def __init__(self):
        self.lines = []

    def __call__(self, text=""):
        self.lines.append(text)

    def block(self, text):
        for l in text.split("\n"):
            self.lines.append(l)

    def text(self):
        return "\n".join(self.lines).rstrip("\n") + "\n"


def guard(fname):
    return fname.replace(".", "_").upper()


def comment_box(title, body_lines, indent=""):
    out = [indent + "/* " + "-" * 94]
    out.append(indent + " * " + title)
    for b in body_lines:
        out.append((indent + " *   " + b).rstrip())
    out.append(indent + " * " + "-" * 94 + " */")
    return "\n".join(out)
