/*
 * EcuM.h
 *
 * [Educational Implementation]
 * Real AUTOSAR counterpart: ECU State Manager, flexible variant (AUTOSAR_CP_SWS_ECUStateManager;
 * EcuM_Init 8.3.2.2, EcuM_StartupTwo 8.3.2.3, EcuM_AL_DriverInitZero/One 8.5.2.x callouts).
 * Implemented states: STARTUP -> (STARTUP_TWO) -> RUN -> POST_RUN -> SHUTDOWN. Not implemented:
 * SLEEP/WAKEUP sources, alarm clock, reset-reason handling, shutdown targets, NvM hooks.
 *
 *   main() { EcuM_Init(); }                         // never returns; ends in StartOS()
 *   EcuM_Init():   MINI target/host pre-OS init -> EcuM_AL_DriverInitZero() -> EcuM_AL_DriverInitOne()
 *                  -> StartOS(OSDEFAULTAPPMODE)
 *   Task_Init (autostart, generated Rte_Tasks.c): EcuM_StartupTwo(); TerminateTask();
 *   EcuM_StartupTwo(): SchM_Init(); BswM_Init(&BswM_Config); (BswM runs the startup action list:
 *                  EcuM_AL_DriverInitTwo, Can/CanIf/PduR/Com init, Rte_Start, mode RUN)
 * Callout names AL_DriverInit* are the real R25-11 callout names; their bodies are GENERATED into
 * EcuM_Cfg.c (agent D) from the config lists EcuMDriverInitListZero/One/Two.
 * Owner: agent C (EcuM.c); EcuM_Cfg.c/.h generated by agent D.
 */
#ifndef ECUM_H
#define ECUM_H

#include "Std_Types.h"
#include "EcuM_Cfg.h"   /* generated: EcuMConf_EcuMFlexUserConfig_* ids */

typedef uint8 EcuM_UserType;
typedef uint8 EcuM_StateType;
#define ECUM_STATE_STARTUP    ((EcuM_StateType)0x10u)
#define ECUM_STATE_RUN        ((EcuM_StateType)0x30u)
#define ECUM_STATE_POST_RUN   ((EcuM_StateType)0x32u)
#define ECUM_STATE_SHUTDOWN   ((EcuM_StateType)0x40u)
#define ECUM_STATE_OFF        ((EcuM_StateType)0x80u)

void           EcuM_Init(void);                 /* MINI_NORETURN in practice: calls StartOS */
void           EcuM_StartupTwo(void);           /* called from Task_Init */
void           EcuM_MainFunction(void);         /* state machine (RUN/POST_RUN/SHUTDOWN); called from a BSW task */
Std_ReturnType EcuM_RequestRUN(EcuM_UserType user);
Std_ReturnType EcuM_ReleaseRUN(EcuM_UserType user);
EcuM_StateType EcuM_GetState(void);
void           EcuM_Shutdown(void);             /* educational: ShutdownOS(E_OK) after ShutdownHook */
void           EcuM_GetVersionInfo(Std_VersionInfoType *versioninfo);
/* [ADDED by agent C] R25-11 8.3.2.1 shutdown entry (minimal: no sleep/halt/poll loop): STATE SHUTDOWN, then ShutdownOS(E_OK) */
Std_ReturnType EcuM_GoDownHaltPoll(uint16 caller);

/* callouts, bodies generated in EcuM_Cfg.c */
void           EcuM_AL_DriverInitZero(void);    /* before OS: Det_Init(&Det_Config), Trace_Init */
void           EcuM_AL_DriverInitOne(void);     /* before OS: Mcu_Init, Mcu_InitClock, Mcu_DistributePllClock, Port_Init, Dio, Adc_Init */
void           EcuM_AL_DriverInitTwo(void);     /* after OS (BswM action): IoHwAb_Init; (Can_Init is done by the CanIf init action) */

#endif /* ECUM_H */
