/*
 * Rte_Dcm.c
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: the part of the generated Rte.c that implements the
 * Dcm's client calls, the SchM_Switch_Dcm_* mode switches and Rte_Start.
 *
 * What the RTE does on Rte_Call for a synchronous server call point when
 * client (Dcm) and server (SW-C runnable) are on the same core/partition:
 * it simply invokes the server runnable - often generated as a direct call
 * or even a macro. If they were on different OS-Applications/cores, the RTE
 * would instead use IOC / activate a task and the call could not complete
 * synchronously; DCM_E_PENDING + OpStatus is the mechanism that lets the
 * Dcm keep polling in that case.
 */
#include "Rte.h"
#include "Rte_Dcm.h"
#include "SchM_Dcm.h"
#include "Rte_VehicleInfoSWC.h"
#include "Rte_SecurityAccessSWC.h"
#include "EcuM.h"
#include "UdsTrace.h"

static Dcm_SesCtrlType Rte_ModeDcmDiagnosticSessionControl = DCM_DEFAULT_SESSION;

static const char *Rte_OpName(Dcm_OpStatusType op)
{
    switch (op) {
    case DCM_INITIAL: return "DCM_INITIAL";
    case DCM_PENDING: return "DCM_PENDING";
    case DCM_CANCEL:  return "DCM_CANCEL";
    default:          return "DCM_FORCE_RCRRP_OK";
    }
}

/* ---------------- Rte lifecycle ---------------- */

void Rte_Start(void)
{
    Rte_ModeDcmDiagnosticSessionControl = DCM_DEFAULT_SESSION;
    UDS_TRACE("Rte", "Rte_Start -> init runnables VehicleInfoSWC_Init, SecurityAccessSWC_Init");
    VehicleInfoSWC_Init();
    SecurityAccessSWC_Init();
}

void Rte_Task_10ms(void)
{
    /* OS task body generated by the RTE: runnables mapped to the 10 ms event. */
    VehicleInfoSWC_Run10ms();
}

/* ---------------- DataServices ---------------- */

Std_ReturnType Rte_Call_DataServices_DID_F190_ReadData(Dcm_OpStatusType OpStatus, uint8 *Data)
{
    Std_ReturnType r;
    UDS_TRACE("Rte", "Rte_Call_DataServices_DID_F190_ReadData(%s) -> server runnable VehicleInfoSWC_ReadVin",
              Rte_OpName(OpStatus));
    r = VehicleInfoSWC_ReadVin(OpStatus, Data);
    UDS_TRACE("Rte", "  <- %s", (r == E_OK) ? "E_OK" : ((r == DCM_E_PENDING) ? "DCM_E_PENDING" : "E_NOT_OK"));
    return r;
}

Std_ReturnType Rte_Call_DataServices_DID_F187_ReadData(uint8 *Data)
{
    UDS_TRACE("Rte", "Rte_Call_DataServices_DID_F187_ReadData -> server runnable VehicleInfoSWC_ReadSwVersion");
    return VehicleInfoSWC_ReadSwVersion(Data);
}

Std_ReturnType Rte_Call_DataServices_DID_F1A0_ReadData(uint8 *Data)
{
    UDS_TRACE("Rte", "Rte_Call_DataServices_DID_F1A0_ReadData -> server runnable VehicleInfoSWC_ReadDiagConfig");
    return VehicleInfoSWC_ReadDiagConfig(Data);
}

Std_ReturnType Rte_Call_DataServices_DID_F1A0_WriteData(const uint8 *Data, Dcm_OpStatusType OpStatus,
                                                        Dcm_NegativeResponseCodeType *ErrorCode)
{
    Std_ReturnType r;
    UDS_TRACE("Rte", "Rte_Call_DataServices_DID_F1A0_WriteData(%s) -> server runnable VehicleInfoSWC_WriteDiagConfig",
              Rte_OpName(OpStatus));
    r = VehicleInfoSWC_WriteDiagConfig(Data, OpStatus, ErrorCode);
    UDS_TRACE("Rte", "  <- %s", (r == E_OK) ? "E_OK" : ((r == DCM_E_PENDING) ? "DCM_E_PENDING" : "E_NOT_OK"));
    return r;
}

/* ---------------- SecurityAccess ---------------- */

Std_ReturnType Rte_Call_SecurityAccess_Level_01_GetSeed(Dcm_OpStatusType OpStatus, uint8 *Seed,
                                                        Dcm_NegativeResponseCodeType *ErrorCode)
{
    UDS_TRACE("Rte", "Rte_Call_SecurityAccess_Level_01_GetSeed(%s) -> SecurityAccessSWC_GetSeed_Level01",
              Rte_OpName(OpStatus));
    return SecurityAccessSWC_GetSeed_Level01(OpStatus, Seed, ErrorCode);
}

Std_ReturnType Rte_Call_SecurityAccess_Level_01_CompareKey(const uint8 *Key, Dcm_OpStatusType OpStatus,
                                                           Dcm_NegativeResponseCodeType *ErrorCode)
{
    UDS_TRACE("Rte", "Rte_Call_SecurityAccess_Level_01_CompareKey(%s) -> SecurityAccessSWC_CompareKey_Level01",
              Rte_OpName(OpStatus));
    return SecurityAccessSWC_CompareKey_Level01(Key, OpStatus, ErrorCode);
}

/* ---------------- RoutineServices ---------------- */

Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_Start(Dcm_OpStatusType OpStatus,
                                                           Dcm_NegativeResponseCodeType *ErrorCode)
{
    UDS_TRACE("Rte", "Rte_Call_RoutineServices_Routine_FF00_Start(%s) -> VehicleInfoSWC_SelfTestStart",
              Rte_OpName(OpStatus));
    return VehicleInfoSWC_SelfTestStart(OpStatus, ErrorCode);
}

Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_Stop(Dcm_OpStatusType OpStatus,
                                                          Dcm_NegativeResponseCodeType *ErrorCode)
{
    UDS_TRACE("Rte", "Rte_Call_RoutineServices_Routine_FF00_Stop(%s) -> VehicleInfoSWC_SelfTestStop",
              Rte_OpName(OpStatus));
    return VehicleInfoSWC_SelfTestStop(OpStatus, ErrorCode);
}

Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_RequestResults(Dcm_OpStatusType OpStatus,
                                                                    uint8 *Out_RoutineStatus,
                                                                    Dcm_NegativeResponseCodeType *ErrorCode)
{
    UDS_TRACE("Rte", "Rte_Call_RoutineServices_Routine_FF00_RequestResults(%s) -> VehicleInfoSWC_SelfTestRequestResults",
              Rte_OpName(OpStatus));
    return VehicleInfoSWC_SelfTestRequestResults(OpStatus, Out_RoutineStatus, ErrorCode);
}

/* ---------------- mode management ---------------- */

void SchM_Switch_Dcm_DcmDiagnosticSessionControl(Dcm_SesCtrlType nextMode)
{
    Rte_ModeDcmDiagnosticSessionControl = nextMode;
    UDS_TRACE("Rte", "SchM_Switch_Dcm_DcmDiagnosticSessionControl(0x%02X): mode users (BswM, SW-Cs) notified",
              (unsigned)nextMode);
}

Dcm_SesCtrlType Rte_Mode_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl(void)
{
    return Rte_ModeDcmDiagnosticSessionControl;
}

void SchM_Switch_Dcm_DcmEcuReset(Rte_ModeType_DcmEcuReset nextMode)
{
    UDS_TRACE("Rte", "SchM_Switch_Dcm_DcmEcuReset(%u)", (unsigned)nextMode);
    if (nextMode == RTE_MODE_DcmEcuReset_EXECUTE) {
        /* Real ECU: BswM is the mode user; a BswM rule triggers an action list
         * (e.g. EcuM_GoDown / Mcu_PerformReset). Here the "BswM role" is inlined. */
        UDS_TRACE("Rte", "  (BswM role) DcmEcuReset=EXECUTE -> EcuM_SimRequestReset");
        EcuM_SimRequestReset();
    }
}
