/*
 * Rte_SecurityAccessSWC.h
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: Rte_<SwcType>.h of the SW-C that provides the
 * SecurityAccess_<Level> port (interface SWS_Dcm_00685). In many real ECUs
 * the seed/key algorithm is instead a Dcm C callout (DcmDspSecurityUsePort =
 * USE_ASYNCH_FNC) or delegated to Csm/HSM; this demo uses the C/S variant.
 */
#ifndef RTE_SECURITYACCESSSWC_H
#define RTE_SECURITYACCESSSWC_H

#include "Rte_Dcm_Type.h"

void SecurityAccessSWC_Init(void);
Std_ReturnType SecurityAccessSWC_GetSeed_Level01(Dcm_OpStatusType OpStatus, uint8 *Seed,
                                                 Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType SecurityAccessSWC_CompareKey_Level01(const uint8 *Key, Dcm_OpStatusType OpStatus,
                                                    Dcm_NegativeResponseCodeType *ErrorCode);

#endif /* RTE_SECURITYACCESSSWC_H */
