/*
 * Rte_VehicleInfoSWC.h
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: the application header Rte_<SwcType>.h that the
 * RTE generator produces for every SW-C type. It contains:
 *   - prototypes of the SW-C's runnables (the RTE calls them)
 *   - the Rte_* API the SW-C may use (Rte_Call / Rte_Mode / Rte_Read ...)
 * A SW-C includes ONLY its own Rte_<Swc>.h - never Dcm.h or NvM.h. That is
 * what makes it portable between ECUs.
 *
 * Server runnables of VehicleInfoSWC (provided ports, interface per DCM SWS):
 *   PPort DataServices_DID_F190    op ReadData   -> VehicleInfoSWC_ReadVin
 *   PPort DataServices_DID_F187    op ReadData   -> VehicleInfoSWC_ReadSwVersion
 *   PPort DataServices_DID_F1A0    op ReadData   -> VehicleInfoSWC_ReadDiagConfig
 *                                  op WriteData  -> VehicleInfoSWC_WriteDiagConfig
 *   PPort RoutineServices_Routine_FF00 ops Start/Stop/RequestResults
 */
#ifndef RTE_VEHICLEINFOSWC_H
#define RTE_VEHICLEINFOSWC_H

#include "Rte_Dcm_Type.h"
#include "NvM.h"

/* ---- runnables (implemented in VehicleInfoSWC.c) ---- */
void VehicleInfoSWC_Init(void);                 /* init runnable (RTE start)        */
void VehicleInfoSWC_Run10ms(void);              /* cyclic runnable, TimingEvent 10ms */
Std_ReturnType VehicleInfoSWC_ReadVin(Dcm_OpStatusType OpStatus, uint8 *Data);
Std_ReturnType VehicleInfoSWC_ReadSwVersion(uint8 *Data);
Std_ReturnType VehicleInfoSWC_ReadDiagConfig(uint8 *Data);
Std_ReturnType VehicleInfoSWC_WriteDiagConfig(const uint8 *Data, Dcm_OpStatusType OpStatus,
                                              Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType VehicleInfoSWC_SelfTestStart(Dcm_OpStatusType OpStatus, Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType VehicleInfoSWC_SelfTestStop(Dcm_OpStatusType OpStatus, Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType VehicleInfoSWC_SelfTestRequestResults(Dcm_OpStatusType OpStatus, uint8 *Out_RoutineStatus,
                                                     Dcm_NegativeResponseCodeType *ErrorCode);

/* ---- Rte API for the SW-C ----
 * Client port "NvM_DiagConfig" to the NvM service (NvMService interface).
 * A real RTE may implement such a call as a direct macro mapping when
 * caller and server are in the same partition - shown here on purpose. */
#define Rte_Call_NvM_DiagConfig_WriteBlock(SrcPtr) \
    NvM_WriteBlock(NvMConf_NvMBlockDescriptor_DiagConfig, (SrcPtr))
#define Rte_Call_NvM_DiagConfig_ReadBlock(DstPtr) \
    NvM_ReadBlock(NvMConf_NvMBlockDescriptor_DiagConfig, (DstPtr))
#define Rte_Call_NvM_DiagConfig_GetErrorStatus(ResultPtr) \
    NvM_GetErrorStatus(NvMConf_NvMBlockDescriptor_DiagConfig, (ResultPtr))

/* Mode port "DcmDiagnosticSessionControl" (RPort, mode user): lets the SW-C
 * know the active diagnostic session without calling Dcm directly. */
Dcm_SesCtrlType Rte_Mode_DcmDiagnosticSessionControl_DcmDiagnosticSessionControl(void);

/* ---- [Educational Implementation] test hook, not an RTE API ---- */
void VehicleInfoSWC_SetVinPendingCycles(uint8 cycles);

#endif /* RTE_VEHICLEINFOSWC_H */
