/*
 * Rte_Dcm.h
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: Rte_Dcm.h. The Dcm is a "service component": it has
 * client ports whose port interfaces are standardized by DCM SWS R20-11 §8.8:
 *   DataServices_<Data>         (C/S, SWS_Dcm_00686)  ReadData / WriteData / ...
 *   SecurityAccess_<Level>      (C/S, SWS_Dcm_00685)  GetSeed / CompareKey
 *   RoutineServices_<Routine>   (C/S, SWS_Dcm_00690)  Start / Stop / RequestResults
 * The RTE generator emits one Rte_Call_<port>_<operation> per configured port.
 * Port names here: DataServices_DID_F190, DataServices_DID_F187,
 * DataServices_DID_F1A0, SecurityAccess_Level_01, RoutineServices_Routine_FF00.
 *
 * Signatures follow the C prototypes of the DCM SWS (Dcm_Externals view,
 * research note 02 §3.9):
 *   ReadData  async     (OpStatus, Data)                          SWS_Dcm_91006
 *   ReadData  sync      (Data)                                    SWS_Dcm_00793
 *   WriteData async fix (Data, OpStatus, ErrorCode)               SWS_Dcm_91008
 *   GetSeed             (OpStatus, Seed, ErrorCode)               SWS_Dcm_91003
 *   CompareKey          (Key, OpStatus, ErrorCode)                SWS_Dcm_91004
 *   Start/Stop/RequestResults (... OpStatus ..., ErrorCode)       SWS_Dcm_01203/01204/91013
 * Real generated headers additionally use compiler abstraction macros and
 * Rte_* typedefs for the array data types (e.g. Dcm_Data17ByteType).
 */
#ifndef RTE_DCM_H
#define RTE_DCM_H

#include "Rte_Dcm_Type.h"

Std_ReturnType Rte_Call_DataServices_DID_F190_ReadData(Dcm_OpStatusType OpStatus, uint8 *Data);
Std_ReturnType Rte_Call_DataServices_DID_F187_ReadData(uint8 *Data);
Std_ReturnType Rte_Call_DataServices_DID_F1A0_ReadData(uint8 *Data);
Std_ReturnType Rte_Call_DataServices_DID_F1A0_WriteData(const uint8 *Data, Dcm_OpStatusType OpStatus,
                                                        Dcm_NegativeResponseCodeType *ErrorCode);

Std_ReturnType Rte_Call_SecurityAccess_Level_01_GetSeed(Dcm_OpStatusType OpStatus, uint8 *Seed,
                                                        Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType Rte_Call_SecurityAccess_Level_01_CompareKey(const uint8 *Key, Dcm_OpStatusType OpStatus,
                                                           Dcm_NegativeResponseCodeType *ErrorCode);

Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_Start(Dcm_OpStatusType OpStatus,
                                                           Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_Stop(Dcm_OpStatusType OpStatus,
                                                          Dcm_NegativeResponseCodeType *ErrorCode);
Std_ReturnType Rte_Call_RoutineServices_Routine_FF00_RequestResults(Dcm_OpStatusType OpStatus,
                                                                    uint8 *Out_RoutineStatus,
                                                                    Dcm_NegativeResponseCodeType *ErrorCode);

#endif /* RTE_DCM_H */
