/*
 * Rte_Dcm_Type.h
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: Rte_Dcm_Type.h. DCM SWS R20-11 places these types
 * there because SW-Cs (via RTE) and Dcm both need them:
 *   Dcm_OpStatusType             SWS_Dcm_00984 (p.301)
 *   Dcm_NegativeResponseCodeType SWS_Dcm_00980 (p.304-307)
 *   Dcm_SesCtrlType              SWS_Dcm_00978 (p.302-303)
 *   Dcm_SecLevelType             SWS_Dcm_00977 (p.302)
 *   Dcm_ConfirmationStatusType   SWS_Dcm_00983 (p.301-302)
 *   Dcm_ProtocolType             SWS_Dcm_00979 (p.303-304)
 */
#ifndef RTE_DCM_TYPE_H
#define RTE_DCM_TYPE_H

#include "Std_Types.h"

/* ---- OpStatus: how Dcm tells the server which call this is ---------- */
typedef uint8 Dcm_OpStatusType;
#define DCM_INITIAL          ((Dcm_OpStatusType)0x00u)  /* first call for this request          */
#define DCM_PENDING          ((Dcm_OpStatusType)0x01u)  /* re-call after DCM_E_PENDING          */
#define DCM_CANCEL           ((Dcm_OpStatusType)0x02u)  /* request aborted, stop and clean up   */
#define DCM_FORCE_RCRRP_OK   ((Dcm_OpStatusType)0x03u)  /* NRC 0x78 forced by app was sent      */

/* ---- Std_ReturnType extensions used by Dcm interfaces (p.338, p.363) */
#define DCM_E_PENDING              ((Std_ReturnType)10u)
#define DCM_E_COMPARE_KEY_FAILED   ((Std_ReturnType)11u)
#define DCM_E_FORCE_RCRRP          ((Std_ReturnType)12u)

/* ---- Negative response codes (subset) ------------------------------ */
typedef uint8 Dcm_NegativeResponseCodeType;
#define DCM_POS_RESP                                   0x00u
#define DCM_E_GENERALREJECT                            0x10u
#define DCM_E_SERVICENOTSUPPORTED                      0x11u
#define DCM_E_SUBFUNCTIONNOTSUPPORTED                  0x12u
#define DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT    0x13u
#define DCM_E_RESPONSETOOLONG                          0x14u
#define DCM_E_BUSYREPEATREQUEST                        0x21u
#define DCM_E_CONDITIONSNOTCORRECT                     0x22u
#define DCM_E_REQUESTSEQUENCEERROR                     0x24u
#define DCM_E_REQUESTOUTOFRANGE                        0x31u
#define DCM_E_SECURITYACCESSDENIED                     0x33u
#define DCM_E_INVALIDKEY                               0x35u
#define DCM_E_EXCEEDNUMBEROFATTEMPTS                   0x36u
#define DCM_E_REQUIREDTIMEDELAYNOTEXPIRED              0x37u
#define DCM_E_GENERALPROGRAMMINGFAILURE                0x72u
#define DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION   0x7Eu
#define DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION       0x7Fu
/* NOTE: 0x78 (requestCorrectlyReceived-ResponsePending) is deliberately NOT
 * part of Dcm_NegativeResponseCodeType in R20-11: a SW-C cannot "return 0x78",
 * it returns DCM_E_PENDING / DCM_E_FORCE_RCRRP and the DSL sends 0x78.
 * The Dcm uses the value internally: */
#define DCM_INTERNAL_NRC_RESPONSEPENDING               0x78u

/* ---- Sessions ------------------------------------------------------- */
typedef uint8 Dcm_SesCtrlType;
#define DCM_DEFAULT_SESSION                    ((Dcm_SesCtrlType)0x01u)
#define DCM_PROGRAMMING_SESSION                ((Dcm_SesCtrlType)0x02u)
#define DCM_EXTENDED_DIAGNOSTIC_SESSION        ((Dcm_SesCtrlType)0x03u)
#define DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION   ((Dcm_SesCtrlType)0x04u)

/* ---- Security levels ------------------------------------------------ */
typedef uint8 Dcm_SecLevelType;
#define DCM_SEC_LEV_LOCKED  ((Dcm_SecLevelType)0x00u)

typedef uint8 Dcm_ConfirmationStatusType;
#define DCM_RES_POS_OK      0x00u
#define DCM_RES_POS_NOT_OK  0x01u
#define DCM_RES_NEG_OK      0x02u
#define DCM_RES_NEG_NOT_OK  0x03u

typedef uint8 Dcm_ProtocolType;
#define DCM_UDS_ON_CAN          ((Dcm_ProtocolType)0x03u)
#define DCM_NO_ACTIVE_PROTOCOL  ((Dcm_ProtocolType)0x0Cu)

/* ---- Mode declaration group DcmEcuReset (values illustrative) ------- */
typedef uint8 Rte_ModeType_DcmEcuReset;
#define RTE_MODE_DcmEcuReset_NONE     0u
#define RTE_MODE_DcmEcuReset_HARD     1u
#define RTE_MODE_DcmEcuReset_SOFT     3u
#define RTE_MODE_DcmEcuReset_EXECUTE  5u

#endif /* RTE_DCM_TYPE_H */
