/*
 * SchM_Dcm.h
 *
 * [Educational Implementation] hand-written "as if generated by the RTE generator".
 * Real AUTOSAR counterpart: SchM_Dcm.h - the BSW-scheduler side of the RTE
 * for the Dcm (Dcm is a BSW module, so it uses SchM_* rather than Rte_* for
 * mode switches; DCM SWS R20-11 SWS_Dcm_00311 names
 * SchM_Switch_<bsnp>_DcmDiagnosticSessionControl). Real SchM_Dcm.h also
 * contains SchM_Enter_Dcm_<ExclusiveArea>/SchM_Exit_... for critical sections;
 * the host demo is single threaded, so they are omitted.
 */
#ifndef SCHM_DCM_H
#define SCHM_DCM_H

#include "Rte_Dcm_Type.h"

/* Mode declaration group DcmDiagnosticSessionControl (mode manager = Dcm). */
void SchM_Switch_Dcm_DcmDiagnosticSessionControl(Dcm_SesCtrlType nextMode);

/* Mode declaration group DcmEcuReset (mode user normally = BswM). */
void SchM_Switch_Dcm_DcmEcuReset(Rte_ModeType_DcmEcuReset nextMode);

#endif /* SCHM_DCM_H */
